import os
import re
import sys

# PlatformIO runs this script via exec() (no __file__); use project dir when set.
REPO_ROOT = os.environ.get("PLATFORMIO_PROJECT_DIR", os.getcwd())
SRC_DIR = os.path.join(REPO_ROOT, "src")

# Embedded /js → PROGMEM headers (same pre-step as HTML so CI / gh_release always has includes).
JS_EMBEDS = [
    ("data/js/inx_font_pack.js", "src/network/html/InxFontPackJs.generated.h", "INX_FONT_PACK_JS", "INXFP"),
    ("data/js/jszip.min.js", "src/network/html/JsZipMinJs.generated.h", "JSZIP_MIN_JS", "INXJZ9"),
    ("data/js/epub_page.js", "src/network/html/EpubPageJs.generated.h", "EPUB_PAGE_JS", "INXEPUB"),
    ("data/js/files_page.js", "src/network/html/FilesPageJs.generated.h", "FILES_PAGE_JS", "INXFILES"),
    ("data/js/qr_creator_logo.min.js", "src/network/html/QrCreatorLogoJs.generated.h", "QR_CREATOR_LOGO_JS",
     "INXQR"),
]


def minify_html(html: str) -> str:
    # Tags where whitespace should be preserved
    preserve_tags = ['pre', 'code', 'textarea', 'script', 'style']
    preserve_regex = '|'.join(preserve_tags)

    # Protect preserve blocks with placeholders
    preserve_blocks = []

    def preserve(match):
        preserve_blocks.append(match.group(0))
        return f"__PRESERVE_BLOCK_{len(preserve_blocks)-1}__"

    html = re.sub(rf'<({preserve_regex})[\s\S]*?</\1>', preserve, html, flags=re.IGNORECASE)

    # Remove HTML comments
    html = re.sub(r'<!--.*?-->', '', html, flags=re.DOTALL)

    # Collapse all whitespace between tags
    html = re.sub(r'>\s+<', '><', html)

    # Collapse multiple spaces inside tags
    html = re.sub(r'\s+', ' ', html)

    # Restore preserved blocks
    for i, block in enumerate(preserve_blocks):
        html = html.replace(f"__PRESERVE_BLOCK_{i}__", block)

    return html.strip()


def write_js_header(js_path: str, out_path: str, array_name: str, delim: str) -> None:
    if not os.path.isfile(js_path):
        print(f"build_html: ERROR missing {js_path}", file=sys.stderr)
        sys.exit(1)

    with open(js_path, "r", encoding="utf-8") as f:
        body = f.read()

    close_seq = f"){delim}"
    if close_seq in body:
        print(f"build_html: ERROR {js_path} contains forbidden {close_seq!r}", file=sys.stderr)
        sys.exit(1)

    out_abs = os.path.join(REPO_ROOT, out_path)
    os.makedirs(os.path.dirname(out_abs), exist_ok=True)
    with open(out_abs, "w", encoding="utf-8") as h:
        h.write("// THIS FILE IS AUTOGENERATED, DO NOT EDIT MANUALLY\n\n")
        h.write("#pragma once\n\n")
        h.write("#include <Arduino.h>\n\n")
        h.write(f'constexpr char {array_name}[] PROGMEM = R"{delim}(')
        h.write(body)
        h.write(f'){delim}";\n')

    print(f"Generated: {out_abs} ({len(body.encode('utf-8'))} bytes)")


def generate_embedded_js() -> None:
    for rel_js, rel_out, array_name, delim in JS_EMBEDS:
        js_path = os.path.join(REPO_ROOT, rel_js)
        write_js_header(js_path, rel_out, array_name, delim)


for root, _, files in os.walk(SRC_DIR):
    for file in files:
        if file.endswith(".html"):
            html_path = os.path.join(root, file)
            with open(html_path, "r", encoding="utf-8") as f:
                html_content = f.read()

            # Removed web pages are no longer part of the navigation. Strip
            # their legacy links from embedded pages as well.
            html_content = re.sub(
                r'<a\b[^>]*href=["\']?/(?:tags|export)["\']?[^>]*>\s*(?:Tags|Bookmarks\s*&(?:amp;)?\s*Annotations)\s*</a>',
                "",
                html_content,
                flags=re.IGNORECASE,
            )

            # Sticky has one fixed chrome layout. Keep the legacy source page
            # compatible with older branches, but do not expose the removed
            # Classic/Bottom Tabs selector in the firmware-served settings UI.
            if file == "SettingsPage.html":
                html_content = re.sub(
                    r'<div\s+class=["\']?setting-item["\']?>\s*'
                    r'<div><div\s+class=["\']?setting-label["\']?>Theme</div></div>\s*'
                    r'<div\s+class=["\']?setting-control["\']?><select\s+id=["\']?uiTheme["\']?></select></div>\s*</div>',
                    "",
                    html_content,
                    flags=re.IGNORECASE,
                )
                html_content = html_content.replace('uiTheme:["Classic","Bottom Tabs"],', "")
                html_content = html_content.replace(
                    'recentLibraryMode:["Grid","Flow","Simple","List","Icons","Cover"]',
                    'recentLibraryMode:["Flow","List","Cover"]')
                html_content = html_content.replace(
                    'optionValues={recentLibraryMode:[0,2,3,4,5,6]',
                    'optionValues={recentLibraryMode:[2,4,6]')
                html_content = html_content.replace(
                    'libraryMode:["List","Grid"]',
                    'libraryMode:["List","Grid","Thumbnail"]')
                # Keep the web controls aligned with the persisted firmware
                # fields.  SettingsPage.html is intentionally compact, so
                # these small source transforms keep the generated page and
                # the firmware API in lockstep without maintaining a second
                # copy of the page.
                html_content = html_content.replace(
                    'sleepScreen:["Dark","Light","Custom","Recent Book","Transparent Cover","None","Date Time"]',
                    'sleepScreen:["Dark","Light","Custom","Recent Book","Transparent Cover","None","Date Time","Widgets"]')
                html_content = html_content.replace(
                    'sleepScreenCoverFilter:["None","Contrast","Inverted"]',
                    'sleepScreenCoverFilter:["None","Grayscale","Inverted"]')
                html_content = html_content.replace(
                    'frontButtonLayout:["Back, Ccnfirm, Left, Right","Left, Right, Back, Confirm","Left, Back, Confirm, Right","Back, Confirm, Right, Left"]',
                    'frontButtonLayout:["Back, Confirm, Left, Right","Left, Right, Back, Confirm","Left, Back, Confirm, Right","Back, Confirm, Right, Left","Left, Right, Confirm, Back"]')
                html_content = html_content.replace(
                    'lineSpacing:["Tight","Normal","Wide","Wider","Loose"]',
                    'lineHeight:["Tight (80%)","Normal (100%)","Wide (120%)","Wider (140%)","Loose (160%)"],textSpace:["Tight (80%)","Normal (100%)","Wide (120%)"]')
                html_content = html_content.replace(
                    'libraryMode:["List","Grid","Thumbnail"]',
                    'libraryMode:["List","Grid","Thumbnail"],librarySortMode:["Title A-Z","Title Z-A","Folder A-Z","Folder Z-A","Author A-Z","Author Z-A"]')
                html_content = html_content.replace(
                    'optionValues={recentLibraryMode:[2,4,6],statusBarFullStyle:[0,7,8,9]}',
                    'optionValues={recentLibraryMode:[2,4,6],lineHeight:[80,100,120,140,160],textSpace:[80,100,120],statusBarFullStyle:[0,7,8,9]}')
                html_content = html_content.replace(
                    'id=lineSpacing',
                    'id=lineHeight')
                html_content = html_content.replace(
                    '<div class=setting-item><div><div class=setting-label>Screen Margin</div>',
                    '<div class=setting-item><div><div class=setting-label>Word spacing</div></div><div class=setting-control><select id=textSpace></select></div></div><div class=setting-item><div><div class=setting-label>Screen Margin</div>')
                html_content = html_content.replace(
                    '<div class=setting-item><div><div class=setting-label>Boot Mode</div>',
                    '<div class=setting-item><div><div class=setting-label>Library sort order</div></div><div class=setting-control><select id=librarySortMode></select></div></div><div class=setting-item><div><div class=setting-label>Boot Mode</div>')
                html_content = html_content.replace(
                    '<div class=setting-item><div><div class=setting-label>Image Quality</div></div><div class=setting-control><select id=readerImageGrayscale></select></div></div>',
                    '<div class=setting-item><div><div class=setting-label>Image Quality</div></div><div class=setting-control><select id=readerImageGrayscale></select></div></div><div class=setting-item><div><div class=setting-label>Smart refresh on images</div></div><div class=setting-control><label class=toggle-switch><input id=readerSmartRefreshOnImages type=checkbox><span class=toggle-slider></span></label></div></div>')
                html_content = html_content.replace(
                    '"bionicReadingEnabled","textAntiAliasing"]',
                    '"bionicReadingEnabled","textAntiAliasing","readerSmartRefreshOnImages"]')
                html_content = html_content.replace(
                    'const e="sleepScreen"!==a||clockAvailable()?options[a]:options[a].slice(0,6),s=optionValues[a]||e.map(function(e,t){return t})',
                    'const e="sleepScreen"!==a||clockAvailable()?options[a]:options[a].filter(function(e,t){return 6!==t}),s=optionValues[a]||("sleepScreen"===a&&!clockAvailable()?e.map(function(e,t){return t>=6?t+1:t}):e.map(function(e,t){return t}))')

            if file == "FontManagerPage.html":
                html_content = html_content.replace(
                    'TTF/OTF → <strong>.bin</strong> (10–18 pt).',
                    'TTF/OTF files are stored on the SD card and rasterized at 8–60 pt on demand.')
                html_content = html_content.replace('Build &amp; upload to SD', 'Upload to SD')
                html_content = re.sub(
                    r'<div style="display:flex;align-items:center;justify-content:space-between;gap:12px;'
                    r'margin:14px 0 16px;padding:12px 14px;border:1px solid #eee;border-radius:12px;'
                    r'background:#fafafa">.*?(?=<button onclick=runFontInstall)',
                    '',
                    html_content,
                    flags=re.DOTALL,
                )
                html_content = html_content.replace(
                    'oneBit:!!document.getElementById("fontOneBitToggle")?.checked,', '')
                html_content = html_content.replace(
                    'r.textContent="Packing "+o+" "+a+"px…"',
                    'r.textContent="Preparing "+o+"…"')
                html_content = html_content.replace(
                    'addModalLog("fontMgrLog",(o.oneBit?"Rasterizing 1-bit fonts":"Rasterizing 2-bit fonts")+" (may take a minute)…","info")',
                    'addModalLog("fontMgrLog","Preparing TTF/OTF files…","info")')
                html_content = html_content.replace(
                    '/\\.bin$/i.test(e.name)',
                    '/\\.(?:bin|ttf|otf)$/i.test(e.name)')
                html_content = html_content.replace('all .bin files inside it?', 'all font files inside it?')

            # minified = regex.sub("\g<1>", html_content)
            minified = minify_html(html_content)
            base_name = f"{os.path.splitext(file)[0]}Html"
            header_path = os.path.join(root, f"{base_name}.generated.h")

            with open(header_path, "w", encoding="utf-8") as h:
                h.write(f"// THIS FILE IS AUTOGENERATED, DO NOT EDIT MANUALLY\n\n")
                h.write(f"#pragma once\n")
                h.write(f'constexpr char {base_name}[] PROGMEM = R"rawliteral({minified})rawliteral";\n')

            print(f"Generated: {header_path}")

generate_embedded_js()
